name: Release

on:
  push:

jobs:
  Release:

    runs-on: windows-latest

    steps:
    - id: get_version
      name: Get version
      uses: jannemattila/get-version-from-tag@v1

    - name: Display version
      run: |
        VERSION=$(echo "${{ steps.get_version.outputs.version }}")
        echo $VERSION
