name: Mahima
on:   
  push:
    branches: [dev]
 
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Step 1
        run: echo "Mahima"
      - name: Step 2
        run: echo "job"
      
    
  


