name: github_workflows
on:   
  push:
    branches: [dev]
 
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Step 1
        run: echo "Download the repo code into the runner"
      - name: Step 2
        run: echo "Display the latest file and contents in Github Actions."
    
