name: github_workflows
on:   
  push:
    branches: [dev]
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: code chekout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  
      - name: Task 2
        run: |
         echo "Display the latest file and contents in Github Actions."
         dir
    
