name: Mahima Katakwar
on:   
  push:
    branches: [dev]

jobs:   
  Mahima: 
    runs-on: windows-latest
    steps: 
      - name: Pune
        run: |
            echo "The newly created file is $Filename"
            echo "The content of newly created file is $FileContent"

        
    
        
    
