name: github_workflows
on:   
  push:
    branches: [dev]
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Task 1
        run: echo "Download the repo code in the runner"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Task 2
        run: echo "Display the latest file and contents in Github Actions."
    
